# Generated by Django 5.2.8 on 2025-12-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_habit_target_count_habitlog_completion_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='target_count',
        ),
    ]
