# Generated by Django 5.2.8 on 2025-11-17 01:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('health', 'Health'), ('productivity', 'Productivity'), ('learning', 'Learning'), ('mindfulness', 'Mindfulness'), ('fitness', 'Fitness'), ('other', 'Other')], default='other', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('completed_today', models.BooleanField(default=False)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-streak', 'name'],
            },
        ),
    ]
