# Generated by Django 5.2.8 on 2025-11-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['category', 'name']},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='created',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='streak',
        ),
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Productivity', 'Productivity'), ('Learning', 'Learning'), ('Mindfulness', 'Mindfulness'), ('Fitness', 'Fitness'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], default='Daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
